# Book configuration
[book]
title = "AkumaKodo Documentation"
description = "A blazing fast discord bot framework built on top of discordeno and typescript!"
authors = ["ThatGuyJamal"]
language = "en"
src = "src"

multilingual = false

# Build configuration
[build]
build-dir = "book"
create-missing = false
use-default-preprocessors = true

#  HTML configuration
[output.html]
git-repository-url = "https://github.com/ThatGuyJamal/AkumaKodo"
edit-url-template = "https://github.com/ThatGuyJamal/AkumaKodo/docs/{path}"

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2